import React from 'react';
import { Link } from 'react-router-dom';

const TermsConditions = () => {
  return (
    <div className="pt-24 bg-white dark:bg-slate-950 min-h-screen">
      <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
        <h1 className="text-3xl md:text-4xl font-bold font-serif text-primary dark:text-white mb-6">Terms & Conditions</h1>
        <p className="text-xs text-slate-400 mb-8">Last Updated: July 4, 2026</p>

        <div className="prose dark:prose-invert text-xs leading-relaxed space-y-6 text-slate-600 dark:text-slate-400">
          <p>
            Welcome to Abacus Homes. These terms and conditions outline the rules and regulations for the use of Abacus Homes' Website, located at abacushomes.com.
          </p>

          <h2 className="text-sm font-bold text-primary dark:text-white uppercase tracking-widest mt-6">1. Acceptance of Terms</h2>
          <p>
            By accessing this website, we assume you accept these terms and conditions in full. Do not continue to use Abacus Homes' website if you do not accept all of the terms and conditions stated on this page.
          </p>

          <h2 className="text-sm font-bold text-primary dark:text-white uppercase tracking-widest mt-6">2. Intellectual Property</h2>
          <p>
            Unless otherwise stated, Abacus Homes owns the intellectual property rights for all material on this site, including architectural drawings, 3D renderings, cost formulas, and blog content. All intellectual property rights are reserved.
          </p>

          <h2 className="text-sm font-bold text-primary dark:text-white uppercase tracking-widest mt-6">3. Estimation & Cost Tool</h2>
          <p>
            Calculations generated by the Cost Calculator page are approximate guidelines. Formal civil engineering bids and structural contracts must be signed in writing by authorized company officers.
          </p>

          <h2 className="text-sm font-bold text-primary dark:text-white uppercase tracking-widest mt-6">4. Client Dashboard</h2>
          <p>
            dashboard accounts are restricted to the designated project owner. You must safeguard your JWT password keys. Unauthorized account sharing is prohibited.
          </p>
        </div>

        <Link to="/" className="inline-block mt-10 text-xs font-bold text-gold uppercase tracking-wider hover:underline">
          ← Back to Home
        </Link>
      </div>
    </div>
  );
};

export default TermsConditions;
