# Generated by Django 6.0.6 on 2026-07-04 02:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.CharField(default='Abacus Editorial', max_length=100)),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.TextField(help_text='Image URL')),
            ],
        ),
        migrations.CreateModel(
            name='CareerPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('department', models.CharField(max_length=100)),
                ('location', models.CharField(default='Bangalore', max_length=100)),
                ('description', models.TextField()),
                ('requirements', models.TextField(help_text='Semicolon-separated requirements')),
            ],
        ),
        migrations.CreateModel(
            name='ConsultationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('location', models.CharField(max_length=255)),
                ('project_type', models.CharField(max_length=100)),
                ('budget', models.CharField(max_length=100)),
                ('land_area', models.CharField(max_length=100)),
                ('plan_url', models.TextField(blank=True, help_text='Uploaded Layout/Plan URL or text', null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='FloorPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('2BHK', '2BHK'), ('3BHK', '3BHK'), ('4BHK', '4BHK'), ('luxury_villas', 'Luxury Villas'), ('duplex', 'Duplex'), ('contemporary', 'Contemporary'), ('modern', 'Modern')], max_length=20)),
                ('bedrooms', models.IntegerField(default=3)),
                ('bathrooms', models.IntegerField(default=3)),
                ('area', models.CharField(help_text='e.g. 2,400 Sq.Ft.', max_length=100)),
                ('image', models.TextField(help_text='Image URL')),
                ('pdf_url', models.TextField(blank=True, help_text='PDF file URL for download', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('luxury_homes', 'Luxury Homes'), ('modern_villas', 'Modern Villas'), ('interiors', 'Interiors'), ('landscaping', 'Landscaping'), ('construction_progress', 'Construction Progress'), ('completed_projects', 'Completed Projects')], max_length=30)),
                ('image', models.TextField(help_text='Image URL')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('residential', 'Residential'), ('commercial', 'Commercial'), ('interior', 'Interior'), ('exterior', 'Exterior'), ('landscape', 'Landscape'), ('renovation', 'Renovation')], max_length=20)),
                ('description', models.TextField()),
                ('location', models.CharField(max_length=255)),
                ('area', models.CharField(help_text='e.g. 4,500 Sq.Ft.', max_length=100)),
                ('duration', models.CharField(help_text='e.g. 12 Months', max_length=100)),
                ('budget', models.CharField(help_text='e.g. $250,000 / Rs 2.5 Crore', max_length=100)),
                ('services_used', models.CharField(help_text='Comma-separated services used', max_length=500)),
                ('before_image', models.TextField(blank=True, help_text='Image URL', null=True)),
                ('after_image', models.TextField(blank=True, help_text='Image URL', null=True)),
                ('progress_timeline', models.JSONField(blank=True, help_text='JSON list of project phases and milestones', null=True)),
                ('client_name', models.CharField(blank=True, max_length=100, null=True)),
                ('client_rating', models.IntegerField(default=5)),
                ('client_review', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('icon', models.CharField(help_text='Lucide icon name (e.g. Ruler, Construction, Palmtree)', max_length=50)),
                ('description', models.TextField()),
                ('details', models.TextField(help_text='Detailed text or semicolon-separated sub-services')),
            ],
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=100)),
                ('client_image', models.TextField(blank=True, help_text='Image URL', null=True)),
                ('rating', models.IntegerField(default=5)),
                ('project_type', models.CharField(help_text='e.g. Villa Owner, Kochi', max_length=100)),
                ('review_text', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='CareerApplication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('resume_url', models.TextField(help_text='Uploaded CV URL or text')),
                ('cover_letter', models.TextField(blank=True, null=True)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('position', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applications', to='core.careerposition')),
            ],
        ),
        migrations.CreateModel(
            name='ClientProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('status', models.CharField(default='In Progress', max_length=100)),
                ('progress_percent', models.IntegerField(default=0)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='projects', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentInvoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('due_date', models.DateField()),
                ('status', models.CharField(choices=[('PAID', 'Paid'), ('PENDING', 'Pending'), ('OVERDUE', 'Overdue')], default='PENDING', max_length=10)),
                ('invoice_url', models.TextField(blank=True, help_text='Invoice PDF download URL', null=True)),
                ('client_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invoices', to='core.clientproject')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('doc_type', models.CharField(choices=[('BLUEPRINTS', 'Blueprints & Drawings'), ('APPROVALS', 'Government Approvals'), ('AGREEMENT', 'Contract Agreement'), ('OTHER', 'Other Documents')], default='BLUEPRINTS', max_length=20)),
                ('file_url', models.TextField(help_text='Document PDF URL')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('client_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='core.clientproject')),
            ],
        ),
        migrations.CreateModel(
            name='ProjectProgressUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('photo_url', models.TextField(help_text='Weekly site image URL')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('client_project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='core.clientproject')),
            ],
        ),
    ]
